FROM node:18-alpine

ARG SHOPIFY_API_KEY
ARG PRODUCER_SHOP_URL
ENV SHOPIFY_API_KEY=$SHOPIFY_API_KEY
ENV PRODUCER_SHOP_URL=$PRODUCER_SHOP_URL
EXPOSE 8081
WORKDIR /app
COPY web .
RUN yarn
RUN cd frontend && yarn && yarn run build
CMD ["yarn", "run", "serve"]
